export enum ActionTypes {
  INCREMENT_COUNTER = 'INCREMENT_COUNTER',
  DECREMENT_COUNTER = 'DECREMENT_COUNTER',
  ADD_TODO = 'ADD_TODO',
  DELETE_TODO = 'DELETE_TODO',
  TOGGLE_TODO = 'TOGGLE_TODO',
  EDIT_TODO = 'EDIT_TODO',
  ADD_SYLLABUSES = 'ADD_SYLLABUSES',
  ADD_SCHEDULE = 'ADD_SCHEDULE',
}
